# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
cache_path = "cache"
auto_detect_solc = false
bytecode_hash = "none"
fuzz = { runs = 10 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
out = "out"
script = "script"
solc = "0.8.30"
src = "src"
test = "test"
cbor_metadata = true
libs = ['lib']
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "excessivelySafeCall/=lib/ExcessivelySafeCall/src/",
  "modulekit/=lib/modulekit/src/",
  "@prb/math/=lib/modulekit/node_modules/@prb/math/src/",
  "@solady/=lib/solady/",
  "@account-abstraction/=lib/modulekit/node_modules/account-abstraction/contracts/",
  "@pigeon/=lib/pigeon/src/",
  "@surl/=lib/surl/src/",
  "@stringutils/=lib/solidity-stringutils/src/",
  "@pendle/=lib/pendle-core-v2-public/contracts/",
  "@safe/=lib/safe-smart-account/contracts/",
  "@safe7579/=lib/safe7579/src/",
  "test/mock_fiattoken/=lib/evm-gateway-contracts/test/mock_fiattoken/"
]
dynamic_test_linking = true
gas_limit = "18446744073709551615"
gas_snapshot_emit= false # Added due to tests in test_extraGas in PaymasterPoC.t.sol
evm_version = "prague"

[profile.ci-sizes]
script = "src"
src = "src"
test = "src"

[profile.coverage]
script = "src"
src = "src"
test = "test"
gas_limit = "18446744073709551615"


[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


