name: "Smart Contracts CI"

env:
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
  FOUNDRY_PROFILE: "ci"
  BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}
  ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
  POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
  AVALANCHE_RPC_URL: ${{ secrets.AVALANCHE_RPC_URL }}
  BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
  FANTOM_RPC_URL: ${{ secrets.FANTOM_RPC_URL }}
  LINEA_RPC_URL: ${{ secrets.LINEA_RPC_URL }}
  BLAST_RPC_URL: ${{ secrets.BLAST_RPC_URL }}
  BSC_RPC_URL_QN: ${{ secrets.BSC_RPC_URL }}
  ARBITRUM_RPC_URL_QN: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL_QN: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL_QN: ${{ secrets.ETHEREUM_RPC_URL }}
  POLYGON_RPC_URL_QN: ${{ secrets.POLYGON_RPC_URL }}
  AVALANCHE_RPC_URL_QN: ${{ secrets.AVALANCHE_RPC_URL }}
  BASE_RPC_URL_QN: ${{ secrets.BASE_RPC_URL }}
  FANTOM_RPC_URL_QN: ${{ secrets.FANTOM_RPC_URL }}
  LINEA_RPC_URL_QN: ${{ secrets.LINEA_RPC_URL }}
  BLAST_RPC_URL_QN: ${{ secrets.BLAST_RPC_URL }}
  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
  TENDERLY_PROJECT_SLUG: "v1" # your project slug
  TENDERLY_ACCOUNT_ID: "superform" # your username or organization name
  FOUNDRY_EXPORTS_OVERWRITE_LATEST: "true"
  OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
  DEBUG_MODE: "false"

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - dev
      - main
      - 'feat/**'
  push:
    branches:
      - dev
      - main
jobs:
  build:
    runs-on: "SuperformCore3"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"
          working-directory: "./contracts"

      - name: Install Dependencies
        run: yarn install
        working-directory: "./contracts"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          working-directory: "./contracts"

      - name: "Install Foundry dependencies"
        run: forge install
        working-directory: "./contracts"

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Check pnpm version"
        run: pnpm --version

      - name: "Install ModuleKit"
        run: pnpm install
        working-directory: "./contracts/lib/modulekit"

      - name: "Build the contracts and print their size"
        working-directory: "./contracts"
        run: "forge build"

      - name: "Add build summary"
        working-directory: "./contracts"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["build"]
    runs-on: "SuperformCore3"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"
          working-directory: "./contracts"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install
        working-directory: "./contracts"

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Check pnpm version"
        run: pnpm --version

      - name: "Install ModuleKit"
        run: pnpm install
        working-directory: "./contracts/lib/modulekit"

      - name: "Show the Foundry config"
        working-directory: "./contracts"
        run: "forge config"

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        working-directory: "./contracts"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: "Run the tests"
        working-directory: "./contracts"
        run: "forge test"

      - name: "Add test summary"
        working-directory: "./contracts"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  deploy-testnet:
    needs: ["build"]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: "SuperformCore3"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.ref_name }}
          
      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"
          working-directory: "./contracts"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install
        working-directory: "./contracts"

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Check pnpm version"
        run: pnpm --version

      - name: "Install ModuleKit"
        run: pnpm install
        working-directory: "./contracts/lib/modulekit"

      - name: "Show the Foundry config"
        working-directory: "./contracts"
        run: "forge config"

      - name: "Install Tenderly CLI"
        run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - name: "Make deploy script executable"
        run: chmod +x ./script/run/deploy_v2_vnet.sh
        working-directory: "./contracts"

      - name: "Run deploy script"
        run: ./script/run/deploy_v2_vnet.sh ${{ github.event.pull_request.number }}
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
        working-directory: "./contracts"