name: "Smart Contracts CI"

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-vnet-counter
  cancel-in-progress: false

env:
  OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
  BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
  TENDERLY_PROJECT_SLUG: "v2"
  TENDERLY_ACCOUNT_ID: "superform"
  FOUNDRY_EXPORTS_OVERWRITE_LATEST: "true"
  ONE_INCH_API_KEY: ${{ secrets.ONE_INCH_API_KEY }}
  CI: "true"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - "feat/**"

jobs:
  build:
    runs-on: "SuperformCore3"
    steps:
      - name: Mask Secrets
        run: |
          echo "::add-mask::${{ secrets.AWS_ROLE_ARN }}"
          echo "::add-mask::${{ secrets.S3_BUCKET_NAME }}"
          echo "::add-mask::${{ secrets.AWS_REGION }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"

      - name: Print ulimits
        run: ulimit -Sa && ulimit -Ha

      - name: Install Dependencies
        run: yarn install

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Get forge version"
        run: forge --version

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Check pnpm version"
        run: pnpm --version

      - name: "Install ModuleKit"
        working-directory: ./lib/modulekit
        run: pnpm install

      - name: "Build the contracts and print their size"
        run: "FOUNDRY_PROFILE=ci-sizes forge build --sizes"

      - name: "Make export ABIs script executable"
        run: chmod +x ./script/run/export_abis_s3.sh

      - name: "Export ABIs to S3"
        run: ./script/run/export_abis_s3.sh "${{ github.ref_name }}" --quiet
        env:
          S3_BUCKET_NAME_ABIS: ${{ secrets.S3_BUCKET_NAME_ABIS }}

      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["build"]
    runs-on: "SuperformCore3"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Install ModuleKit"
        working-directory: ./lib/modulekit
        run: pnpm install
        
      - name: "Install merkle-js dependencies"
        working-directory: ./test/utils/merkle/merkle-js
        run: npm install

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: "Run the tests"
        run: "make ftest-vvv"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  vnet-deploy:
    needs: ["test"]
    if:
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/feat/'))
    runs-on: "SuperformCore3"
    outputs:
      eth_mainnet_addresses: ${{ steps.get-addresses-eth.outputs.addresses }}
      base_mainnet_addresses: ${{ steps.get-addresses-base.outputs.addresses }}
      optimism_mainnet_addresses: ${{ steps.get-addresses-optimism.outputs.addresses }}
    steps:
      # -------------------------------------------------------------------
      # Block for OIDC
      # -------------------------------------------------------------------
      - name: Mask Secrets
        run: |
          echo "::add-mask::${{ secrets.AWS_ROLE_ARN }}"
          echo "::add-mask::${{ secrets.S3_BUCKET_NAME }}"
          echo "::add-mask::${{ secrets.AWS_REGION }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      # -------------------------------------------------------------------

      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Install ModuleKit"
        working-directory: ./lib/modulekit
        run: pnpm install

      - name: "Install Tenderly CLI"
        run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - name: "Install jq"
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: "Make deploy script executable"
        run: chmod +x ./script/run/deploy_v2_vnet_s3.sh

      - name: Get branch name and commit hash
        id: branch-info
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: "Run deploy script"
        run: ./script/run/deploy_v2_vnet_s3.sh "$BRANCH_NAME"
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Get deployed addresses for Ethereum
        id: get-addresses-eth
        run: |
          ADDRESSES=$(cat ./script/output/1/Ethereum-latest.json | jq -c .)
          echo "addresses=$ADDRESSES" >> $GITHUB_OUTPUT

      - name: Get deployed addresses for Base
        id: get-addresses-base
        run: |
          ADDRESSES=$(cat ./script/output/8453/Base-latest.json | jq -c .)
          echo "addresses=$ADDRESSES" >> $GITHUB_OUTPUT

      - name: Get deployed addresses for Optimism
        id: get-addresses-optimism
        run: |
          ADDRESSES=$(cat ./script/output/10/Optimism-latest.json | jq -c .)
          echo "addresses=$ADDRESSES" >> $GITHUB_OUTPUT

      - name: Add deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Ethereum Mainnet (Chain ID: 1)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ./script/output/1/Ethereum-latest.json | jq . >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Base (Chain ID: 8453)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ./script/output/8453/Base-latest.json | jq . >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Optimism (Chain ID: 10)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ./script/output/10/Optimism-latest.json | jq . >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  coverage:
    runs-on: SuperformCore3
    needs: ["test"]
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Install ModuleKit"
        working-directory: ./lib/modulekit
        run: pnpm install
        
      - name: "Install merkle-js dependencies"
        working-directory: ./test/utils/merkle/merkle-js
        run: npm install

      - name: "Generate the coverage report using unit and integration tests"
        run: "make coverage"

      - name: "Upload coverage report to Codecov"
        uses: "codecov/codecov-action@v5"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: "./lcov.info"

      - name: "Add coverage summary"
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
