name: "Smart Contracts CI"

env:
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
  FOUNDRY_PROFILE: "ci"
  BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}
  ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
  POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
  AVALANCHE_RPC_URL: ${{ secrets.AVALANCHE_RPC_URL }}
  BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
  FANTOM_RPC_URL: ${{ secrets.FANTOM_RPC_URL }}
  LINEA_RPC_URL: ${{ secrets.LINEA_RPC_URL }}
  BLAST_RPC_URL: ${{ secrets.BLAST_RPC_URL }}
  BSC_RPC_URL_QN: ${{ secrets.BSC_RPC_URL }}
  ARBITRUM_RPC_URL_QN: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL_QN: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL_QN: ${{ secrets.ETHEREUM_RPC_URL }}
  POLYGON_RPC_URL_QN: ${{ secrets.POLYGON_RPC_URL }}
  AVALANCHE_RPC_URL_QN: ${{ secrets.AVALANCHE_RPC_URL }}
  BASE_RPC_URL_QN: ${{ secrets.BASE_RPC_URL }}
  FANTOM_RPC_URL_QN: ${{ secrets.FANTOM_RPC_URL }}
  LINEA_RPC_URL_QN: ${{ secrets.LINEA_RPC_URL }}
  BLAST_RPC_URL_QN: ${{ secrets.BLAST_RPC_URL }}
  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
  TENDERLY_PROJECT_SLUG: "v1" # your project slug
  TENDERLY_ACCOUNT_ID: "superform" # your username or organization name
  FOUNDRY_EXPORTS_OVERWRITE_LATEST: "true"
  OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
  DEBUG_MODE: "false"

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - dev
      - main
      - 'feat/**'
  push:
    branches:
      - dev
      - 'feat/**'

jobs:
  build:
    runs-on: "SuperformCore3"
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"

      - name: Install Dependencies
        run: yarn install

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Check pnpm version"
        run: pnpm --version

      - name: "Install ModuleKit"
        working-directory: ./contracts/lib/modulekit
        run: pnpm install

      - name: "Build the contracts and print their size"
        run: "forge build"

      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["build"]
    runs-on: "SuperformCore3"
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Check pnpm version"
        run: pnpm --version

      - name: "Install ModuleKit"
        working-directory: ./contracts/lib/modulekit
        run: pnpm install

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: "Run the tests"
        run: "forge test"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  vnet-deploy:
    needs: ["test"]
    if: |
      (github.event_name == 'pull_request' && (startsWith(github.head_ref, 'feat/') || github.base_ref == 'dev')) ||
      (github.event_name == 'push' && (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/feat/')))
    runs-on: "SuperformCore3"
    defaults:
      run:
        working-directory: ./contracts
    outputs:
      eth_mainnet_addresses: ${{ steps.get-addresses-eth.outputs.addresses }}
      base_mainnet_addresses: ${{ steps.get-addresses-base.outputs.addresses }}
      optimism_mainnet_addresses: ${{ steps.get-addresses-optimism.outputs.addresses }}
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Install ModuleKit"
        working-directory: ./contracts/lib/modulekit
        run: pnpm install

      - name: "Install Tenderly CLI"
        run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - name: "Make deploy script executable"
        run: chmod +x ./script/run/deploy_v2_vnet.sh

      - name: Get PR number and commit hash
        id: pr-info
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            echo "COMMIT_HASH=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "PR_NUMBER=0" >> $GITHUB_ENV
            echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: "Run deploy script"
        run: ./script/run/deploy_v2_vnet.sh $PR_NUMBER $COMMIT_HASH
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}

      - name: Get deployed addresses for Ethereum
        id: get-addresses-eth
        run: |
          ADDRESSES=$(cat ./script/output/1/Ethereum-latest.json)
          echo "addresses=$ADDRESSES" >> $GITHUB_OUTPUT

      - name: Get deployed addresses for Base
        id: get-addresses-base
        run: |
          ADDRESSES=$(cat ./script/output/8453/Base-latest.json)
          echo "addresses=$ADDRESSES" >> $GITHUB_OUTPUT

      - name: Get deployed addresses for Optimism
        id: get-addresses-optimism
        run: |
          ADDRESSES=$(cat ./script/output/10/Optimism-latest.json)
          echo "addresses=$ADDRESSES" >> $GITHUB_OUTPUT

      - name: Add deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Ethereum Mainnet (Chain ID: 1)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ./script/output/1/Ethereum-latest.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Base (Chain ID: 8453)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ./script/output/8453/Base-latest.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "### Optimism (Chain ID: 10)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ./script/output/10/Optimism-latest.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY