name: "Smart Contracts CI"

env:
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
  FOUNDRY_PROFILE: "ci"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v1"

      - name: "Install the Node.js dependencies"
        working-directory: "./contracts"
        run: "bun install"

      - name: "Lint the code"
        working-directory: "./contracts"
        run: "bun run lint"

      - name: "Add lint summary"
        working-directory: "./contracts"
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 'latest'
          working-directory: "./contracts" 

      - name: Install Dependencies
        run: yarn install
        working-directory: "./contracts"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          working-directory: "./contracts"

      - name: "Install Foundry dependencies"
        run: forge install
        working-directory: "./contracts"

      - name: "Install ModuleKit"
        run: pnpm install
        working-directory: "./contracts/lib/modulekit"

      - name: "Build the contracts and print their size"
        working-directory: "./contracts"
        run: "forge build --sizes"

      - name: "Add build summary"
        working-directory: "./contracts"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["lint", "build"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v1"

      - name: "Install the Node.js dependencies"
        working-directory: "./contracts"
        run: "bun install"

      - name: "Show the Foundry config"
        working-directory: "./contracts"
        run: "forge config"

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        working-directory: "./contracts"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: "Run the tests"
        working-directory: "./contracts"
        run: "forge test"

      - name: "Add test summary"
        working-directory: "./contracts"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
