name: "Relayer CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.22.x ]
        goarch: [ "amd64" ]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: "Lint"
        uses: "golangci/golangci-lint-action@v6"
        with:
          version: v1.59.1
          working-directory: "./relayer"

  test-unit:
    needs: ["lint"]
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.22.x ]
        goarch: [ "amd64" ]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: "Test"
        working-directory: "./relayer"
        run: "make test-unit"

      - name: "Archive code coverage results"
        uses: "actions/upload-artifact@v3"
        with:
          name: code-coverage-report
          path: ./relayer/coverage.out

