name: "Validate PR source branch"

on:
  pull_request:
    branches:
      - dev

jobs:
  validate-branch-name:
    name: Ensure branch name starts with feat/
    runs-on: ubuntu-latest
    steps:
      - name: Check branch naming convention
        run: |
          # github.head_ref is the feature branch name
          if [[ ! "${{ github.head_ref }}" =~ ^feat\/ ]]; then
            echo "::error ::ðŸš¨ Branch name '${{ github.head_ref }}' is invalid."
            echo "::error ::Your pull request source branch must be named feat/... to merge into dev."
            exit 1
          fi
